### ISSUE TITLE
The mathematical principle of “offset” during create vehicles randomly，in kinematics.py

### ISSUE THREAD

**Issue by sweet-jin** [Farama-Foundation/HighwayEnv#438]
hello, I don't understand the mathematical principle of getting “offset”.

"offset = spacing * default_spacing * np.exp(-5 / 40 * len(road.network.graph[_from][_to]))"

Why do I need to multiply “np.exp(-5 / 40 * len(road.network.graph[_from][_to])” here？
Thank you very much！

**Comment by eleurent** [comment]
Hi,
This is just a heuristic way of accounting for the fact that when the road has more lane we don't need as much longitudinal space between vehicles, since we can spread them in the lateral direction instead.
This is very empirical, exp(-n_lanes) is just a decreasing function that starts at 1 and converges to 0, I could have taken something else like 1/n_lanes^2.

If you can still adjust the spacing manually for each road to correct for this effect if you don't like it.

**Comment by sweet-jin** [comment]
I get it. Thanks!
