### ISSUE TITLE
The PPO default parameters do not work well

### ISSUE THREAD

**Issue by shile1998** [Farama-Foundation/HighwayEnv#441]
After using the PPO default parameters, the image and actual effect are not good, and it cannot be effectively overtaken
![2023-03-27 17-45-57 的屏幕截图](https://user-images.githubusercontent.com/92363567/227909039-fcd2d094-c549-41b7-9428-8585756283d4.png)

**Comment by eleurent** [comment]
It's been a while since I ran this, but I think PPO gets okay-ish performance with the default env parameters, as in it mostly stays alive but does not drive very aggressively. For a stronger behaviour, I would advise trying different observation types and/or model architectures, see https://highway-env.readthedocs.io/en/latest/faq.html

**Comment by eleurent** [comment]
Also see comparison to the performance with DQN: https://farama-foundation.github.io/HighwayEnv/quickstart/#id4
I think you get comparable results with PPO, so while this is not optimal you should still get reasonable behaviours (the agent tries to stay alive, and occasionally overtakes)

**Comment by eleurent** [comment]
Closing this for now since results seem as expected and can be improved further by obs/model changes. Let me know if you have more questions.
