### ISSUE TITLE
Some question about the "Kinematics" when I set the action to "ContinuousAction"

### ISSUE THREAD

**Issue by haijime-w** [Farama-Foundation/HighwayEnv#445]
Thank you for your work!!! In the process of learning, I have the following questions.

In the racetrack environment, I set the action to "ContinuousAction", and if I set "observation" to "OccupancyGrid", I find that I can easily train an agent to finish a lap.
But when I set "observation" to "Kinematics"and its "features" are ["x", "y", "vx", "vy", "heading"], I find that I can't train an agent who can run long distances, and the agent always walks a few paces and then becomes stationary. That's true no matter how much I change the reward.
I wonder , is it because "Kinematics" doesn't fit "ContinuousAction" at all,? Or do i need a perfect reward?

**Comment by eleurent** [comment]
I guess it would be harder with this `Kinematrics` observation because the model doesn't get to observe the road geometry directly (contrary to `OccupancyGrid`, which can): it can only observe the (x,y) locations of the vehicle which lead to penalties (off-road), so it has to memorise the entire track a posteriori.

You can probably make its job much easier by including the following additional features: `'long_off', 'lat_off', 'ang_off'`
See https://github.com/Farama-Foundation/HighwayEnv/blob/2523ea2aecb6ef7399e2c1df573c461e44e1125f/highway_env/vehicle/kinematics.py#L215

In particular, `lat_off` and `ang_off` tell the model how much the vehicle deviates from the lane centreline, so that should be quite useful for lane-tracking.

**Comment by haijime-w** [comment]
THX!!!!!
I will try it.
