### ISSUE TITLE
“speed_limit” does not work

### ISSUE THREAD

**Issue by Zheng-Guang-Zhang** [Farama-Foundation/HighwayEnv#449]
hello,thanks for your great work.I set a road which contain 4 lanes.
```
y = [0, 4, 8, 12]
for i in range(3):
       net.add_lane("f", "c", StraightLane([sum(ends[:2]), y[i]], [sum(ends[:3]), y[i]], line_types=line_type_ready[i])) #speed_limit=35
net.add_lane("f", "c", StraightLane([sum(ends[:2]), 12], [sum(ends[:3]), 12], speed_limit=22, line_types=[s,c]))   #speed_limit=22
```
but the speed of agent is still high in rightmost lane,which indicates that the ‘speed_limit=22’ does not work.

**Comment by eleurent** [comment]
You're right, currently `speed_limit` isn't exactly used as a speed limit as its name suggests, it is merely used to initialise the target speed of random vehicles (when no speed is explicitly set), but once they change lane they will keep following this target / other vehicles with higher initial speed targets can still enter the lane. It is also used in the road regulation mechanism at intersections, but it's pretty minor.

I will make it such that the target speed of IDM vehicles is clipped at the lane's speed limit, that should be closer to the expected behaviour.

**Comment by Zheng-Guang-Zhang** [comment]
I see,thanks!
