### ISSUE TITLE
SAC, TD3 don't work on parking-v0 environment

### ISSUE THREAD

**Issue by CCodie** [Farama-Foundation/HighwayEnv#473]
Hi, thank you for your awesome code.

Now I'm trying to run 'parking-v0' task with SAC and TD3 algorithm.
But it seems that training doesn't work properly because even after millions of training steps, the success rate is still around 0.

Here're the versions what I'm using.
```
gym                     0.21.0      
gymnasium               0.28.1
highway-env             1.8.1
stable-baselines3       2.0.0a5
```

I trained the algorithms with their default hyper parameters, and also with parameters setting in example script. (https://github.com/Farama-Foundation/HighwayEnv/blob/master/scripts/parking_her.ipynb)

Now I'm confused whether SAC and TD3 are not the right ones for parking task or this just happened because of wrong version of code.

Can you give me some advice ? Thank you !

**Comment by eleurent** [comment]
Yes I noticed this also recently (https://github.com/Farama-Foundation/HighwayEnv/issues/457). As far as I can tell, this is caused by a PR which changed the parking environment by adding walls, and which this seems to make the task much more difficult for some reason.

You can try to disable walls like this
```env = gym.make('parking-v0', config=dict(add_walls=False))```

Let me know if this improves performance. If so, maybe it would be better to make this option the default.

**Comment by ZhangyuHuang** [comment]
Hello! I also met the same problem.I tried your code to solve it
`env = gym.make('parking-v0', config=dict(add_walls=False))`
and then I tried to render this env,
`env = gym.make('parking-v0', config=dict(add_walls=False))`
`env.reset()`
`plt.imshow(env.render())`
`plt.show()`
`env.close()`
it also shows the walls. I don't know why.
The link of screenshot is below:
https://drive.google.com/file/d/1lnFjFgB2DX3QkzEVkLYQlgzzCCfwN8d_/view?usp=share_link

**Comment by eleurent** [comment]
Hi, sorry this was caused by a bug (the config was introduced in the PR but not being used). I fixed it recently in https://github.com/Farama-Foundation/HighwayEnv/commit/0a174bef8b9418c8e7fea80d662b017d4a83cb31, but this hasnt made it yet into a release.
I'll try to make one soon, but meanwhile you can install the dev (HEAD) version

**Comment by ZhangyuHuang** [comment]
Yeah, I used your fixed version, it works!
Besides, I found the training problem of parking-v0 is not the walls, the problem is the collision_reward.
In the current parking-v0, the collision_reward is set to -500 which is very low.
So I set the collision_reward to -5 like your past version, and the training result is pretty well. The success_rate reached 95% even 97%

**Comment by eleurent** [comment]
Oh nice, that's great! I have no idea why I set the collision reward to such a low value, probably a mistake. But thanks a lot for letting me know, I'll fix it! :)

**Comment by CCodie** [comment]
@eleurent thank you for the quick reply, @ZhangyuHuang and thank you for the comment !
Those are really helpful :)

I trained the parking-v0 with no_wall=True option, and it converged to about 1.00 success_rate within 200k of learning steps.

And I trained with the walls but changed collision_reward from -500 to -5 as @ZhangyuHuang mentioned, it also successfully converged to about 1.00 of success_rate after 800k~1m steps.

Thanks!

**Comment by eleurent** [comment]
>  it also successfully converged to about 1.00 of success_rate after 800k~1m steps.

that looks like a lot of steps though, you can get to 0.95-1.0 in just 50k, see for instance [this colab](https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/parking_her.ipynb) (roughly 30mn of training time)
