### ISSUE TITLE
Question about Minimum Speed

### ISSUE THREAD

**Issue by favu100** [Farama-Foundation/HighwayEnv#491]
Hello,

somehow I have the feeling that the RL agent in the highway environment has a minimum speed of 20 m/s.
However, other vehicles might drive slower. Is it possible to allow slower speeds than 20 m/s, ideally adapting to the speed of the car in front. 
Otherwise, there could be situations where collisions are predictable; but still cannot be avoided.

**Comment by eleurent** [comment]
Hi,
In principle the situation that you are describing shouldn't occur that often, because the other vehicles are all created with a target speed samples randomly in [23, 25]. 

But I agree that it's still possible, so if you are concerned about this you can edit the list of speed targets spanned by the DiscreteMetaAction action space. for example,

`env.configure({"action": {"target_speeds": [10, 25, 30]}})`

(The default is [20, 25, 30]).

**Comment by favu100** [comment]
Okay, thank you!

**Comment by favu100** [comment]
Likewise, is there a minimum speed for vehicles other than the ego vehicle? By default, it is 20 m/s for the Ego Vehicle

**Comment by eleurent** [comment]
Not really, other vehicles are typically IDMVehicles, and their minimum speed is 0 because they will brake if there is an obstacle in front of them. However, in the absence of any obstacle, they will try to reach their `target_speed`, which can be set to anything. They shouldn't have any incentive to go faster.

**Comment by favu100** [comment]
Thank you!
