### ISSUE TITLE
Question On Finding Closest Lane Lines

### ISSUE THREAD

**Issue by MasonN808** [Farama-Foundation/HighwayEnv#492]
Hi,

I'm working in the parking environment and would like to get the distance from a controlled vehicle to the closest lane lines. I've been searching for a combination of methods in the repo that may be able to do the job, but I'm unable to find them if they exist.
Is this even possible in this environment? I can get the positioning of the lanes themselves, but not the actual lines which would most likely be implemented as an n-dimensional numpy array discretizing the continuous lines for each Lane object. This discretization would encode the position of a single point on the lane line.

**Comment by MasonN808** [comment]
I ended up getting the initial and end positions of the lane lines via the parameters of the StraightLane() object and simply executed the below code segment to obtain the quantized positionings of the continuous straight lines.

```   
def _quantize_straight_line_positions(self, init_line_position: list, end_line_position: list, num_points: int) -> np.ndarray:
        assert num_points > 0, "num_points must be strictly greater than zero'"
        quantized_line_positions = []
        # Initial positioning of the quantized point on the line
        x_pos = init_line_position[0]
        y_pos = init_line_position[1]
        for _ in range(num_points):
            longitudinal_diff = (init_line_position[0]-end_line_position[0])/num_points
            lateral_diff = (init_line_position[1]-end_line_position[1])/num_points
            x_pos += longitudinal_diff
            y_pos += lateral_diff
            quantized_line_positions.append([x_pos, y_pos])
        return np.array(quantized_line_positions)`

**Comment by eleurent** [comment]
You can get the (longitudinal, lateral) coordinates of the vehicle relative to a lane with

long, lat = lane.local_coordinates(vehicle.position)

Then, since the lane centerline is described by 0 <= long <= lane.length and lat=0, the distance from the vehicle to this curve is simply

dist = np.sqrt(max(max(-long, 0) max(long - lane.length, 0))**2 + lat**2)

If you instead want to compute a list or quantised centerline positions as you suggested, you can do it with

[lane.position(l, 0) for l in np.linspace(0, lane.length, 100)]
