### ISSUE TITLE
Ensuring no collisions among background vehicles when increasing traffic density?

### ISSUE THREAD

**Issue by xiaofutongxuo** [Farama-Foundation/HighwayEnv#520]
Hello,

Recently, I've been experimenting with the intersection and roundabout environments, specifically aiming to conduct reinforcement learning training under varying traffic densities. To achieve this, I tried increasing the number of vehicles in the environment, hoping to simulate a heavier traffic scenario.

However, I observed that as I increase the number of background vehicles, they tend to collide with each other more frequently. This in turn affects the training of the ego vehicle, as the background vehicle collisions create an unrealistic driving scenario.

In real-world road conditions, drivers typically avoid collisions and ensure safe driving. I'd love to replicate a similar scenario in this simulation environment.

Could you offer any methods or suggestions on how to ensure that background vehicles do not collide with each other while maintaining increased traffic density, thereby providing a more realistic training scenario for the ego vehicle?

Thank you so much for your time and consideration. I look forward to your response!

Best regards！

**Comment by potatohhs** [comment]
It seems that we are doing the similar research luckily. For the problem, generally speaking, the IDMVehicle module can avoid collisions. Shall we talk about it with email？

**Comment by xiaofutongxuo** [comment]
Of course! My email address is 2022224122@chd.edu.cn .

**Comment by eleurent** [comment]
Hi @xiaofutongxuo,

Yes I have noticed this issue as well.
The IDM / MOBIL models are guaranteed to avoid collisions I think, but they only apply to straight roads and but not to any other road network configuration (merge, intersection, roundabout, etc.).
- Remark 1: Even on straight road segments, the MOBIL model assumes that lane changes are instantaneous which is not the case in highway-env. This introduces a possibility for collisions: vehicle A starts a lane change and cuts into the lane of vehicle B because the maxium decceleration that B would incur is below the safety threshold, but in practice it can take 1-2s before the lane change is complete. During maneuver, the merging vehicle A would not be "visible" by vehicle B, so it would keep accelerating or driving at constant speed instead of decelerating, which could result in a collision. I have some code trying to deal with this issue (checking whether there is a vehicle currently trying to merge into a vehicle's lane), but I don't guarantee it covers 100% of use cases.
- Remark 2: for other situations it's even more difficult. In some cases I only make the assumption that the lanes are parallel, which is partially true and works somewhat (e.g. roundabout, or merge). In other scenarios, like intersection, I implemented a very simplistic collision avoidance mechanism based on predicting the future (2s) position of any vehicle (assuming constant speed), and setting the target speed to 0 whenever a collision is predicted in the next 2s. This is only a very crude mechanism and does not avoid collisions in all situations.


I think it would be quite difficult to find a perfect collision avoidance policy (as difficult as writing a working L5 autonomous driving software, really), and for my own work  I was focusing on accounting for the effect of social interactions, so I didnt need the simulator to be fully realistic...


I mentioned this issue [in the docs](https://highway-env.farama.org/environments/intersection/), and I welcome any PR that would improve the realism of the simulator without degrading the computing time too much.

Finally, there is a trick that I used when working with high-density scenarios: simply disable collision checks for all but controlled vehicles, meaning controlled vehicle will collide with all other vehicles, but other vehicles will not collide between themselves.

Here is an example where this is implemented:

https://github.com/Farama-Foundation/HighwayEnv/blob/86320a3197bc622700bad1145a5b96f439c2c234/highway_env/envs/highway_env.py#L145

**Comment by xiaofutongxuo** [comment]
> It seems that we are doing the similar research luckily. For the problem, generally speaking, the IDMVehicle module can avoid collisions. Shall we talk about it with email？

Of course! My email address is 2022224122@chd.edu.cn

**Comment by xiaofutongxuo** [comment]
Big thanks for getting back to me! @eleurent 

I’ve got a few thoughts about the aforementioned points and I'm not sure if they’re feasible:

- **Real-world Traffic Data**: I've noticed that the vehicles can't always completely avoid obstacles in the simulations. This got me thinking - could we incorporate real-world traffic data into the environment, since actual human driving doesn't involve collisions (well, most of the time)? Could this work, or is there another way to implement it?
- **Mixing It Up with Other Simulator**: I stumbled upon a [paper](https://www.nature.com/articles/s41467-021-21007-8) where the authors used **CARLA** and **highway-env** together for joint simulations（in the 23rd reference of the paper, they cited one of your articles）. Unfortunately, they didn't share the specifics. Have you come across something like this, or have any tips on connecting highway-env with other simulation environments like **CARLA**?

**Comment by eleurent** [comment]
> Real-world Traffic Data: I've noticed that the vehicles can't always completely avoid obstacles in the simulations. This got me thinking - could we incorporate real-world traffic data into the environment, since actual human driving doesn't involve collisions (well, most of the time)? Could this work, or is there another way to implement it?

Maybe this would be suitable for some specific, but not for the focus of highway-env, which is modelling interactions behind vehicles. That is, if the autonomous vehicle takes a decision, it needs to understand that (and how) it will impact others, and take it into account while planning. When replaying traffic data, other vehicles do not adapt to what the ego-vehicle does, it would be like driving while being invisible to other traffic participants, which is difficult and dangerous.

> Mixing It Up with Other Simulator: I stumbled upon a [paper](https://www.nature.com/articles/s41467-021-21007-8) where the authors used CARLA and highway-env together for joint simulations（in the 23rd reference of the paper, they cited one of your articles）. Unfortunately, they didn't share the specifics. Have you come across something like this, or have any tips on connecting highway-env with other simulation environments like CARLA?

The point of highway-env is also to be simple and minimalist. If you're going to use something fancier like CARLA, you might as well use it on its own :)
