### ISSUE TITLE
Racetrack Environment Problem

### ISSUE THREAD

**Issue by mozturan** [Farama-Foundation/HighwayEnv#521]
Hello, sorry to bother. I'm trying to solve racetrack env with duble-dqn using keras/tf. I use kinematics as observations.

My problem with this environment is when i train my model with default returns (reward, done, info...) the agent goes off the road since there is no terminal defined for off-road. So this situation makes it not learn anything at all. (even though i use "'offroad_terminal': True" in configuration there is no terminal) 

On the other hand when i put some terminal for off-road, since my reward is a scalar pointing to the distance to the lane center, agent seems to follow the lane but it always crashes to the vehicle on the same lane. That means agent can't change its lane cuz when training it mostly doesn't know on which lane it is and lane changing is a off-road situation for it.

Is there someone worked with this environment? Is there any solution to that? Is there something i can do? Or maybe i'm just missing a point to fix it? 

Thanks everyone for your helps.

BTW: I tried to turn this environment to lane following task only by removing the npc vehicle using "other_vehicles": 0 in env.configure but i ended up with some error. I believe this might be a bug or is there any other way to do this?

**Comment by eleurent** [comment]
Hi,

First of all, have you tried running https://github.com/Farama-Foundation/HighwayEnv/blob/master/scripts/sb3_racetracks_ppo.py ? This should result in a policy able to solve the task.

>  I use kinematics as observations.

Then ensure that you enabled the features allowing the agent to locate the lanes, i.e. lateral offset and heading offset.
Also make sure that the observation contains the relative/absolute position of the other vehicle.

> the agent goes off the road since there is no terminal defined for off-road. So this situation makes it not learn anything at all. (even though i use "'offroad_terminal': True" in configuration there is no terminal)

You're right, this is supported by the highway env but not the racetrack env, I should add it. But the reward function should be enough of an incentive for the agent to stay onroad, if the agent is not able to learn from it there might be something wrong with the setup.

> BTW: I tried to turn this environment to lane following task only by removing the npc vehicle using "other_vehicles": 0 in env.configure but i ended up with some error. I believe this might be a bug or is there any other way to do this?

This should also work, and its the proper way, can you share the error that you get?

**Comment by mehmetozturan** [comment]
Hi again, thanks for your answer but i think the problem remains. 

> Then ensure that you enabled the features allowing the agent to locate the lane, i.e. lateral offset and heading offset.
Also make sure that the observation contains the relative/absolute position of the other vehicle.

I already use these features, so my config is like:
```
{'action': {'lateral': True,
            'longitudinal': False,
            'target_speeds': [0, 5],
            'type': 'ContinuousAction'},
 'action_reward': -0.3,
 'centering_position': [0.5, 0.5],
 'collision_reward': -1,
 'controlled_vehicles': 1,
 'duration': 300,
 'lane_centering_cost': 4,
 'lane_centering_reward': 1,
 'manual_control': False,
 'observation': {'features': ['presence',
                              'x',
                              'y',
                              'vx',
                              'vy',
                              'cos_h',
                              'sin_h',
                              'heading',
                              'long_off',
                              'lat_off',
                              'ang_off'],
                 'type': 'Kinematics',
                 'vehicles_count': 1},
 'offscreen_rendering': False,
 'other_vehicles': 2,
 'other_vehicles_type': 'highway_env.vehicle.behavior.IDMVehicle',
 'policy_frequency': 5,
 'real_time_rendering': False,
 'render_agent': True,
 'scaling': 5.5,
 'screen_height': 600,
 'screen_width': 600,
 'show_trajectories': True,
 'simulation_frequency': 15}`
```
**I also try to run with grayscale images and CNN architecture but result are same. I tried to run for longer episodes and tried to adjust some parameters but it didn't work.**

> You're right, this is supported by the highway env but not the racetrack env, I should add it. But the reward function should be enough of an incentive for the agent to stay onroad, if the agent is not able to learn from it there might be something wrong with the setup.

I handle this in main code with:
```
if info["on_road_reward"] == False:
         done = True
         reward = -1.0
```

> First of all, have you tried running https://github.com/Farama-Foundation/HighwayEnv/blob/master/scripts/sb3_racetracks_ppo.py ? This should result in a policy able to solve the task.
 
I was able to run the code with no changes and after training the results i get is literally same with my own code. **The agent is able to follow road after training but it always crashes.** So `sb3_racetracks_ppo.py`  can't solve the task. As you see after training result of `sb3_racetracks_ppo.py` ( my tensorflow dqn code also has the same result)

https://github.com/Farama-Foundation/HighwayEnv/assets/89272933/c87cf669-e1e5-474f-bf08-d9b639fad99e

Since PPO and my DQN have the same result and agent can learn following the road but it always crashes, i think the problem might be the environment. I can't understand why and how yet.

And environment can be used for lane following task but as i said i cant change 'other_vehicles' value so i only have just my agent in this environment: 

> This should also work, and its the proper way, can you share the error that you get?

The Default `other_vehicles` value is `1`. When i configure the environment with `other_vehicles=0` (or any other integer) it seam okay but then i get some error at  `env.reset()`:

- If i set `other_vehicles` value to `0` i get `ValueError: high <= 0` (at  `env.reset()`)
- But weirdly if i set `other_vehicles` value to something > 1 (for exp. 5) i get `AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'` (at  `env.reset()`)

So, in the end:
- Agent can't solve task properly
- Can't remove other vehicles or change number of other vehicles in environment

Sorry it took so long :) but if there is any solution to this problems please let me know. Thanks for your attention!

**Comment by eleurent** [comment]
Hi, I apologize for the late reply.

> Since PPO and my DQN have the same result and agent can learn following the road but it always crashes, i think the problem might be the environment. I can't understand why and how yet.

I agree that if several algorithms fail to learn in the same way it's a bit suspicious. I would manually inspect some trajectories and verify that the three following properties hold:
- that the agent could have applied other actions to avoid the collision
- that the observations are correct, and can be used to predict the collision (e.g. we see the vehicles getting closer and closer, and the velocity information is also there)
- that the reward correctly penalizes the collision (and rewards avoiding it)

If one of these is not satisfied then its a bug in the environment, otherwise it's probably an issue with the agent.
But unfortunately I don't have a lot of time to investigate these days :/

> numpy.random._generator.Generator' object has no attribute 'randint' (at env.reset())

I'll try to fix this
