### ISSUE TITLE
Encouraging the car to follow the correct direction

### ISSUE THREAD

**Issue by PGG106** [Farama-Foundation/HighwayEnv#536]
Hi!, I'm trying to work with the racetrack environment, for the action choice i'm using a very basic DQN.
I've noticed that the model is more or less capable of learning, but even when the reward starts getting decently high the agent doesn't perform as expected.
The current way my model maximizes the reward is simply avoiding to go offroad and avoiding collisions, it does so by spinning in place and only moving out of the way when another car approaches, it will also often try to move in the wrong direction (going left instead of right when spawning).
Is there any way to set the reward as to encourage it to follow the road more?

**Comment by PGG106** [comment]
Duplicated the question on discord

**Comment by eleurent** [comment]
It looks like your agent is doing reward hacking: it found an undesirable way of increasing the reward function. The usual solution is to patch the reward function such that it penalises this undesirable behaviour, and rewards even more the correct behaviour. For instance, you could reward positively the projection of the vehicle's velocity on the lane's forward direction. This way, the vehicle is penalised for driving backward (and thus for spinning).

Something like

```
longitudinal, _ = self.vehicle.lane.local_coordinates(self.vehicle.position)
lane_heading = lane.heading_at(longitudinal)
lane_direction = np.array([np.cos(lane_heading), np.sin(lane_heading)])
forward_velocity = np.dot(self.vehicle.velocity, lane_direction)
reward = 1.0 * forward_velocity
```

**Comment by PGG106** [comment]
Thank you so much for the tip, my best attempt for now has been to penalize the agent if it picks the same action too many times in a row but your idea seems a lot more solid.

**Comment by eleurent** [comment]
I think in principle there is no reason why it shouldn't work, but in practice many things can matter. For example, it could be that it is easier to learn a policy than it is to learn a value function for that particular problem. I don't have that much experience in using discrete actions for continuous control task, I think one possible pitfall is that the action duration is typically quite short, meaning that the action values will be very similar because all actions have a very limited instantaneous impact and tend to lead to roughly the same state... While this is not a problem in principle (the best action should still have higher value), you may run into numerical approximation limits faster than if you try to estimate the policy directly.
The actual choice of action set probably matters a lot, you need to make sure that it is large enough that the agent can always control the vehicle correctly, but not too large otherwise the exploration will be harder.
